// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package mapping

import (
	"context"
	"database/sql"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (
    monitor_id,
    status,
    status_code,
    latency,
    error
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, monitor_id, status, status_code, latency, error, checked_at
`

type CreateCheckParams struct {
	MonitorID  int64          `json:"monitor_id"`
	Status     int64          `json:"status"`
	StatusCode sql.NullInt64  `json:"status_code"`
	Latency    sql.NullInt64  `json:"latency"`
	Error      sql.NullString `json:"error"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (*Check, error) {
	row := q.db.QueryRowContext(ctx, createCheck,
		arg.MonitorID,
		arg.Status,
		arg.StatusCode,
		arg.Latency,
		arg.Error,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.StatusCode,
		&i.Latency,
		&i.Error,
		&i.CheckedAt,
	)
	return &i, err
}

const deleteOldChecks = `-- name: DeleteOldChecks :exec
DELETE FROM checks
WHERE checked_at < ?1
`

func (q *Queries) DeleteOldChecks(ctx context.Context, before string) error {
	_, err := q.db.ExecContext(ctx, deleteOldChecks, before)
	return err
}

const getCheckBeforeIDByStatus = `-- name: GetCheckBeforeIDByStatus :one
SELECT c.id, c.monitor_id, c.status, c.status_code, c.latency, c.error, c.checked_at
FROM checks c
WHERE c.monitor_id = ?1
  AND c.status = ?2
  AND c.id < ?3
ORDER BY c.id DESC
LIMIT 1
`

type GetCheckBeforeIDByStatusParams struct {
	MonitorID int64 `json:"monitor_id"`
	Status    int64 `json:"status"`
	ID        int64 `json:"id"`
}

func (q *Queries) GetCheckBeforeIDByStatus(ctx context.Context, arg GetCheckBeforeIDByStatusParams) (*Check, error) {
	row := q.db.QueryRowContext(ctx, getCheckBeforeIDByStatus, arg.MonitorID, arg.Status, arg.ID)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.StatusCode,
		&i.Latency,
		&i.Error,
		&i.CheckedAt,
	)
	return &i, err
}

const getCheckById = `-- name: GetCheckById :one
SELECT c.id, c.monitor_id, c.status, c.status_code, c.latency, c.error, c.checked_at
FROM checks c
WHERE c.id = ?1
`

func (q *Queries) GetCheckById(ctx context.Context, id int64) (*Check, error) {
	row := q.db.QueryRowContext(ctx, getCheckById, id)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.StatusCode,
		&i.Latency,
		&i.Error,
		&i.CheckedAt,
	)
	return &i, err
}

const getCheckStatsByMonitorSince = `-- name: GetCheckStatsByMonitorSince :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(SUM(CASE WHEN status = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS ok
FROM checks
WHERE monitor_id = ?1
  AND checked_at >= ?2
`

type GetCheckStatsByMonitorSinceParams struct {
	MonitorID int64  `json:"monitor_id"`
	Since     string `json:"since"`
}

type GetCheckStatsByMonitorSinceRow struct {
	Total int64 `json:"total"`
	Ok    int64 `json:"ok"`
}

func (q *Queries) GetCheckStatsByMonitorSince(ctx context.Context, arg GetCheckStatsByMonitorSinceParams) (*GetCheckStatsByMonitorSinceRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckStatsByMonitorSince, arg.MonitorID, arg.Since)
	var i GetCheckStatsByMonitorSinceRow
	err := row.Scan(&i.Total, &i.Ok)
	return &i, err
}

const getLatestCheckByMonitor = `-- name: GetLatestCheckByMonitor :one
SELECT c.id, c.monitor_id, c.status, c.status_code, c.latency, c.error, c.checked_at
FROM checks c
WHERE c.monitor_id = ?1
ORDER BY c.checked_at DESC, c.id DESC
LIMIT 1
`

func (q *Queries) GetLatestCheckByMonitor(ctx context.Context, monitorID int64) (*Check, error) {
	row := q.db.QueryRowContext(ctx, getLatestCheckByMonitor, monitorID)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.StatusCode,
		&i.Latency,
		&i.Error,
		&i.CheckedAt,
	)
	return &i, err
}

const listChecksByMonitor = `-- name: ListChecksByMonitor :many
SELECT c.id, c.monitor_id, c.status, c.status_code, c.latency, c.error, c.checked_at
FROM checks c
WHERE c.monitor_id = ?1
ORDER BY c.checked_at DESC, c.id DESC
LIMIT ?2
`

type ListChecksByMonitorParams struct {
	MonitorID  int64 `json:"monitor_id"`
	LimitCount int64 `json:"limit_count"`
}

func (q *Queries) ListChecksByMonitor(ctx context.Context, arg ListChecksByMonitorParams) ([]*Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecksByMonitor, arg.MonitorID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Status,
			&i.StatusCode,
			&i.Latency,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecksByMonitorSince = `-- name: ListChecksByMonitorSince :many
SELECT c.id, c.monitor_id, c.status, c.status_code, c.latency, c.error, c.checked_at
FROM checks c
WHERE c.monitor_id = ?1
  AND c.checked_at >= ?2
ORDER BY c.checked_at DESC, c.id DESC
`

type ListChecksByMonitorSinceParams struct {
	MonitorID int64  `json:"monitor_id"`
	Since     string `json:"since"`
}

func (q *Queries) ListChecksByMonitorSince(ctx context.Context, arg ListChecksByMonitorSinceParams) ([]*Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecksByMonitorSince, arg.MonitorID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Status,
			&i.StatusCode,
			&i.Latency,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
