// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package mapping

import (
	"context"
	"database/sql"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    monitor_id,
    title,
    message
) VALUES (
    ?1,
    ?2,
    ?3
) RETURNING id, monitor_id, title, message, started_at, resolved_at
`

type CreateIncidentParams struct {
	MonitorID int64  `json:"monitor_id"`
	Title     string `json:"title"`
	Message   string `json:"message"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (*Incident, error) {
	row := q.db.QueryRowContext(ctx, createIncident, arg.MonitorID, arg.Title, arg.Message)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Title,
		&i.Message,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const deleteOldResolvedIncidents = `-- name: DeleteOldResolvedIncidents :exec
DELETE FROM incidents
WHERE resolved_at IS NOT NULL
  AND resolved_at < ?1
`

func (q *Queries) DeleteOldResolvedIncidents(ctx context.Context, before sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldResolvedIncidents, before)
	return err
}

const getOpenIncidentByMonitor = `-- name: GetOpenIncidentByMonitor :one
SELECT id, monitor_id, title, message, started_at, resolved_at
FROM incidents
WHERE monitor_id = ?1
  AND resolved_at IS NULL
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetOpenIncidentByMonitor(ctx context.Context, monitorID int64) (*Incident, error) {
	row := q.db.QueryRowContext(ctx, getOpenIncidentByMonitor, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Title,
		&i.Message,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const listIncidentsByMonitorIDsSince = `-- name: ListIncidentsByMonitorIDsSince :many
SELECT
    i.id,
    i.monitor_id,
    m.name AS monitor_name,
    i.title,
    i.message,
    i.started_at,
    i.resolved_at
FROM incidents i
JOIN monitors m ON m.id = i.monitor_id
WHERE i.monitor_id = ?1
  AND (
    i.resolved_at IS NULL
    OR i.started_at >= ?2
    OR (i.resolved_at IS NOT NULL AND i.resolved_at >= ?2)
  )
ORDER BY
    CASE WHEN i.resolved_at IS NULL THEN 0 ELSE 1 END,
    COALESCE(i.resolved_at, i.started_at) DESC
`

type ListIncidentsByMonitorIDsSinceParams struct {
	MonitorID int64  `json:"monitor_id"`
	Since     string `json:"since"`
}

type ListIncidentsByMonitorIDsSinceRow struct {
	ID          int64          `json:"id"`
	MonitorID   int64          `json:"monitor_id"`
	MonitorName string         `json:"monitor_name"`
	Title       string         `json:"title"`
	Message     string         `json:"message"`
	StartedAt   string         `json:"started_at"`
	ResolvedAt  sql.NullString `json:"resolved_at"`
}

func (q *Queries) ListIncidentsByMonitorIDsSince(ctx context.Context, arg ListIncidentsByMonitorIDsSinceParams) ([]*ListIncidentsByMonitorIDsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentsByMonitorIDsSince, arg.MonitorID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListIncidentsByMonitorIDsSinceRow{}
	for rows.Next() {
		var i ListIncidentsByMonitorIDsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.MonitorName,
			&i.Title,
			&i.Message,
			&i.StartedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOpenIncidentByMonitor = `-- name: ResolveOpenIncidentByMonitor :one
UPDATE incidents
SET resolved_at = datetime('now')
WHERE id = (
    SELECT i.id
    FROM incidents i
    WHERE i.monitor_id = ?1
      AND i.resolved_at IS NULL
    ORDER BY i.id DESC
    LIMIT 1
)
RETURNING id, monitor_id, title, message, started_at, resolved_at
`

func (q *Queries) ResolveOpenIncidentByMonitor(ctx context.Context, monitorID int64) (*Incident, error) {
	row := q.db.QueryRowContext(ctx, resolveOpenIncidentByMonitor, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Title,
		&i.Message,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return &i, err
}
