// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mapping

import (
	"database/sql"
)

type Check struct {
	ID         int64          `json:"id"`
	MonitorID  int64          `json:"monitor_id"`
	Status     int64          `json:"status"`
	StatusCode sql.NullInt64  `json:"status_code"`
	Latency    sql.NullInt64  `json:"latency"`
	Error      sql.NullString `json:"error"`
	CheckedAt  string         `json:"checked_at"`
}

type Incident struct {
	ID         int64          `json:"id"`
	MonitorID  int64          `json:"monitor_id"`
	Title      string         `json:"title"`
	Message    string         `json:"message"`
	StartedAt  string         `json:"started_at"`
	ResolvedAt sql.NullString `json:"resolved_at"`
}

type Monitor struct {
	ID            int64  `json:"id"`
	UserID        string `json:"user_id"`
	Name          string `json:"name"`
	Type          string `json:"type"`
	Target        string `json:"target"`
	Interval      int64  `json:"interval"`
	Timeout       int64  `json:"timeout"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     string `json:"created_at"`
	NextCheckAt   string `json:"next_check_at"`
	Confirmations int64  `json:"confirmations"`
}

type MonitorNotification struct {
	MonitorID      int64 `json:"monitor_id"`
	NotificationID int64 `json:"notification_id"`
}

type MonitorUptimeHourly struct {
	MonitorID int64  `json:"monitor_id"`
	HourStart string `json:"hour_start"`
	Ok        int64  `json:"ok"`
	Total     int64  `json:"total"`
}

type Notification struct {
	ID      int64  `json:"id"`
	UserID  string `json:"user_id"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
}

type StatusPage struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	Public int64  `json:"public"`
}

type StatusPageMonitor struct {
	StatusPageID int64 `json:"status_page_id"`
	MonitorID    int64 `json:"monitor_id"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	Status       string         `json:"status"`
	ApiKey       sql.NullString `json:"api_key"`
	LastLoginAt  sql.NullString `json:"last_login_at"`
	LastLoginIp  sql.NullString `json:"last_login_ip"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}
