// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package mapping

import (
	"context"
	"database/sql"
)

const claimDueMonitors = `-- name: ClaimDueMonitors :many
UPDATE monitors
SET next_check_at = datetime('now', '+' || interval || ' seconds')
WHERE id IN (
    SELECT id
    FROM monitors
    WHERE enabled = 1
      AND next_check_at <= datetime('now')
    ORDER BY next_check_at ASC
    LIMIT ?1
)
RETURNING id, user_id, name, type, target, interval, timeout, enabled, created_at, next_check_at, confirmations
`

func (q *Queries) ClaimDueMonitors(ctx context.Context, limitCount int64) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, claimDueMonitors, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Interval,
			&i.Timeout,
			&i.Enabled,
			&i.CreatedAt,
			&i.NextCheckAt,
			&i.Confirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    user_id,
    name,
    type,
    target,
    interval,
    timeout,
    enabled,
    confirmations
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
) RETURNING id, user_id, name, type, target, interval, timeout, enabled, created_at, next_check_at, confirmations
`

type CreateMonitorParams struct {
	UserID        string `json:"user_id"`
	Name          string `json:"name"`
	Type          string `json:"type"`
	Target        string `json:"target"`
	Interval      int64  `json:"interval"`
	Timeout       int64  `json:"timeout"`
	Enabled       int64  `json:"enabled"`
	Confirmations int64  `json:"confirmations"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (*Monitor, error) {
	row := q.db.QueryRowContext(ctx, createMonitor,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.Interval,
		arg.Timeout,
		arg.Enabled,
		arg.Confirmations,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.Interval,
		&i.Timeout,
		&i.Enabled,
		&i.CreatedAt,
		&i.NextCheckAt,
		&i.Confirmations,
	)
	return &i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE id = ?1
  AND user_id = ?2
`

type DeleteMonitorParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error {
	_, err := q.db.ExecContext(ctx, deleteMonitor, arg.ID, arg.UserID)
	return err
}

const getMonitorById = `-- name: GetMonitorById :one
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
WHERE m.id = ?1
`

func (q *Queries) GetMonitorById(ctx context.Context, id int64) (*Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitorById, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.Interval,
		&i.Timeout,
		&i.Enabled,
		&i.CreatedAt,
		&i.NextCheckAt,
		&i.Confirmations,
	)
	return &i, err
}

const getMonitorByIdAndUser = `-- name: GetMonitorByIdAndUser :one
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
WHERE m.id = ?1
  AND m.user_id = ?2
`

type GetMonitorByIdAndUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMonitorByIdAndUser(ctx context.Context, arg GetMonitorByIdAndUserParams) (*Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitorByIdAndUser, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.Interval,
		&i.Timeout,
		&i.Enabled,
		&i.CreatedAt,
		&i.NextCheckAt,
		&i.Confirmations,
	)
	return &i, err
}

const listEnabledMonitors = `-- name: ListEnabledMonitors :many
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
WHERE m.enabled = 1
ORDER BY m.id
`

func (q *Queries) ListEnabledMonitors(ctx context.Context) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Interval,
			&i.Timeout,
			&i.Enabled,
			&i.CreatedAt,
			&i.NextCheckAt,
			&i.Confirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledMonitorsByUser = `-- name: ListEnabledMonitorsByUser :many
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
WHERE m.user_id = ?1
  AND m.enabled = 1
ORDER BY m.id
`

func (q *Queries) ListEnabledMonitorsByUser(ctx context.Context, userID string) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Interval,
			&i.Timeout,
			&i.Enabled,
			&i.CreatedAt,
			&i.NextCheckAt,
			&i.Confirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
WHERE m.user_id = ?1
ORDER BY m.created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID string) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Interval,
			&i.Timeout,
			&i.Enabled,
			&i.CreatedAt,
			&i.NextCheckAt,
			&i.Confirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name           = COALESCE(?1, name),
    type           = COALESCE(?2, type),
    target         = COALESCE(?3, target),
    interval       = COALESCE(?4, interval),
    timeout        = COALESCE(?5, timeout),
    enabled        = COALESCE(?6, enabled),
    confirmations  = COALESCE(?7, confirmations)
WHERE id = ?8
  AND user_id = ?9
RETURNING id, user_id, name, type, target, interval, timeout, enabled, created_at, next_check_at, confirmations
`

type UpdateMonitorParams struct {
	Name          sql.NullString `json:"name"`
	Type          sql.NullString `json:"type"`
	Target        sql.NullString `json:"target"`
	Interval      sql.NullInt64  `json:"interval"`
	Timeout       sql.NullInt64  `json:"timeout"`
	Enabled       sql.NullInt64  `json:"enabled"`
	Confirmations sql.NullInt64  `json:"confirmations"`
	ID            int64          `json:"id"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (*Monitor, error) {
	row := q.db.QueryRowContext(ctx, updateMonitor,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.Interval,
		arg.Timeout,
		arg.Enabled,
		arg.Confirmations,
		arg.ID,
		arg.UserID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.Interval,
		&i.Timeout,
		&i.Enabled,
		&i.CreatedAt,
		&i.NextCheckAt,
		&i.Confirmations,
	)
	return &i, err
}
