// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor_notifications.sql

package mapping

import (
	"context"
)

const attachNotificationToMonitor = `-- name: AttachNotificationToMonitor :exec
INSERT INTO monitor_notifications (monitor_id, notification_id)
VALUES (?1, ?2)
`

type AttachNotificationToMonitorParams struct {
	MonitorID      int64 `json:"monitor_id"`
	NotificationID int64 `json:"notification_id"`
}

func (q *Queries) AttachNotificationToMonitor(ctx context.Context, arg AttachNotificationToMonitorParams) error {
	_, err := q.db.ExecContext(ctx, attachNotificationToMonitor, arg.MonitorID, arg.NotificationID)
	return err
}

const detachNotificationFromMonitor = `-- name: DetachNotificationFromMonitor :exec
DELETE FROM monitor_notifications
WHERE monitor_id = ?1
  AND notification_id = ?2
`

type DetachNotificationFromMonitorParams struct {
	MonitorID      int64 `json:"monitor_id"`
	NotificationID int64 `json:"notification_id"`
}

func (q *Queries) DetachNotificationFromMonitor(ctx context.Context, arg DetachNotificationFromMonitorParams) error {
	_, err := q.db.ExecContext(ctx, detachNotificationFromMonitor, arg.MonitorID, arg.NotificationID)
	return err
}

const listEnabledNotificationsByMonitor = `-- name: ListEnabledNotificationsByMonitor :many
SELECT n.id, n.user_id, n.type, n.config, n.enabled
FROM notifications n
JOIN monitor_notifications mn ON mn.notification_id = n.id
WHERE mn.monitor_id = ?1
  AND n.enabled = 1
ORDER BY n.id
`

func (q *Queries) ListEnabledNotificationsByMonitor(ctx context.Context, monitorID int64) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledNotificationsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByNotification = `-- name: ListMonitorsByNotification :many
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
JOIN monitor_notifications mn ON mn.monitor_id = m.id
WHERE mn.notification_id = ?1
ORDER BY m.id
`

func (q *Queries) ListMonitorsByNotification(ctx context.Context, notificationID int64) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorsByNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Interval,
			&i.Timeout,
			&i.Enabled,
			&i.CreatedAt,
			&i.NextCheckAt,
			&i.Confirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByMonitor = `-- name: ListNotificationsByMonitor :many
SELECT n.id, n.user_id, n.type, n.config, n.enabled
FROM notifications n
JOIN monitor_notifications mn ON mn.notification_id = n.id
WHERE mn.monitor_id = ?1
ORDER BY n.id
`

func (q *Queries) ListNotificationsByMonitor(ctx context.Context, monitorID int64) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
