// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package mapping

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    type,
    config,
    enabled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, user_id, type, config, enabled
`

type CreateNotificationParams struct {
	UserID  string `json:"user_id"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.Enabled,
	)
	return &i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = ?1
  AND user_id = ?2
`

type DeleteNotificationParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT n.id, n.user_id, n.type, n.config, n.enabled
FROM notifications n
WHERE n.id = ?1
`

func (q *Queries) GetNotificationById(ctx context.Context, id int64) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationById, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.Enabled,
	)
	return &i, err
}

const getNotificationByIdAndUser = `-- name: GetNotificationByIdAndUser :one
SELECT n.id, n.user_id, n.type, n.config, n.enabled
FROM notifications n
WHERE n.id = ?1
  AND n.user_id = ?2
`

type GetNotificationByIdAndUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNotificationByIdAndUser(ctx context.Context, arg GetNotificationByIdAndUserParams) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByIdAndUser, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.Enabled,
	)
	return &i, err
}

const listEnabledNotificationsByUser = `-- name: ListEnabledNotificationsByUser :many
SELECT n.id, n.user_id, n.type, n.config, n.enabled
FROM notifications n
WHERE n.user_id = ?1
  AND n.enabled = 1
ORDER BY n.id
`

func (q *Queries) ListEnabledNotificationsByUser(ctx context.Context, userID string) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT n.id, n.user_id, n.type, n.config, n.enabled
FROM notifications n
WHERE n.user_id = ?1
ORDER BY n.id DESC
`

func (q *Queries) ListNotificationsByUser(ctx context.Context, userID string) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotification = `-- name: UpdateNotification :one
UPDATE notifications
SET type    = COALESCE(?1, type),
    config  = COALESCE(?2, config),
    enabled = COALESCE(?3, enabled)
WHERE id = ?4
  AND user_id = ?5
RETURNING id, user_id, type, config, enabled
`

type UpdateNotificationParams struct {
	Type    sql.NullString `json:"type"`
	Config  sql.NullString `json:"config"`
	Enabled sql.NullInt64  `json:"enabled"`
	ID      int64          `json:"id"`
	UserID  string         `json:"user_id"`
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotification,
		arg.Type,
		arg.Config,
		arg.Enabled,
		arg.ID,
		arg.UserID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.Enabled,
	)
	return &i, err
}
