// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mapping

import (
	"context"
	"database/sql"
)

type Querier interface {
	AttachMonitorToStatusPage(ctx context.Context, arg AttachMonitorToStatusPageParams) error
	AttachNotificationToMonitor(ctx context.Context, arg AttachNotificationToMonitorParams) error
	ClaimDueMonitors(ctx context.Context, limitCount int64) ([]*Monitor, error)
	CreateCheck(ctx context.Context, arg CreateCheckParams) (*Check, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (*Monitor, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (*Notification, error)
	CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (*StatusPage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOldChecks(ctx context.Context, before string) error
	DeleteStatusPage(ctx context.Context, arg DeleteStatusPageParams) error
	DeleteUser(ctx context.Context, id string) error
	DetachMonitorFromStatusPage(ctx context.Context, arg DetachMonitorFromStatusPageParams) error
	DetachNotificationFromMonitor(ctx context.Context, arg DetachNotificationFromMonitorParams) error
	GetCheckBeforeIDByStatus(ctx context.Context, arg GetCheckBeforeIDByStatusParams) (*Check, error)
	GetCheckById(ctx context.Context, id int64) (*Check, error)
	GetCheckStatsByMonitorSince(ctx context.Context, arg GetCheckStatsByMonitorSinceParams) (*GetCheckStatsByMonitorSinceRow, error)
	GetLatestCheckByMonitor(ctx context.Context, monitorID int64) (*Check, error)
	GetListUser(ctx context.Context) ([]*User, error)
	GetListUserByRole(ctx context.Context, role string) ([]*User, error)
	GetMonitorById(ctx context.Context, id int64) (*Monitor, error)
	GetMonitorByIdAndUser(ctx context.Context, arg GetMonitorByIdAndUserParams) (*Monitor, error)
	GetNotificationById(ctx context.Context, id int64) (*Notification, error)
	GetNotificationByIdAndUser(ctx context.Context, arg GetNotificationByIdAndUserParams) (*Notification, error)
	GetPublicStatusPageBySlug(ctx context.Context, slug string) (*StatusPage, error)
	GetStatusPageById(ctx context.Context, id int64) (*StatusPage, error)
	GetStatusPageByIdAndUser(ctx context.Context, arg GetStatusPageByIdAndUserParams) (*StatusPage, error)
	GetStatusPageBySlug(ctx context.Context, slug string) (*StatusPage, error)
	GetUserByAPIKey(ctx context.Context, apiKey sql.NullString) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id string) (*User, error)
	GetUserByUserName(ctx context.Context, username string) (*User, error)
	GetUserSelectList(ctx context.Context, name interface{}) ([]*GetUserSelectListRow, error)
	ListChecksByMonitor(ctx context.Context, arg ListChecksByMonitorParams) ([]*Check, error)
	ListChecksByMonitorSince(ctx context.Context, arg ListChecksByMonitorSinceParams) ([]*Check, error)
	ListEnabledMonitors(ctx context.Context) ([]*Monitor, error)
	ListEnabledMonitorsByUser(ctx context.Context, userID string) ([]*Monitor, error)
	ListEnabledNotificationsByMonitor(ctx context.Context, monitorID int64) ([]*Notification, error)
	ListEnabledNotificationsByUser(ctx context.Context, userID string) ([]*Notification, error)
	ListMonitorsByNotification(ctx context.Context, notificationID int64) ([]*Monitor, error)
	ListMonitorsByStatusPage(ctx context.Context, statusPageID int64) ([]*Monitor, error)
	ListMonitorsByUser(ctx context.Context, userID string) ([]*Monitor, error)
	ListNotificationsByMonitor(ctx context.Context, monitorID int64) ([]*Notification, error)
	ListNotificationsByUser(ctx context.Context, userID string) ([]*Notification, error)
	ListStatusPagesByMonitor(ctx context.Context, monitorID int64) ([]*StatusPage, error)
	ListStatusPagesByUser(ctx context.Context, userID string) ([]*StatusPage, error)
	SetActive(ctx context.Context, id string) error
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (*Monitor, error)
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (*Notification, error)
	UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (*StatusPage, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
