// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_page_monitors.sql

package mapping

import (
	"context"
)

const attachMonitorToStatusPage = `-- name: AttachMonitorToStatusPage :exec
INSERT INTO status_page_monitors (status_page_id, monitor_id)
VALUES (?1, ?2)
`

type AttachMonitorToStatusPageParams struct {
	StatusPageID int64 `json:"status_page_id"`
	MonitorID    int64 `json:"monitor_id"`
}

func (q *Queries) AttachMonitorToStatusPage(ctx context.Context, arg AttachMonitorToStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, attachMonitorToStatusPage, arg.StatusPageID, arg.MonitorID)
	return err
}

const detachMonitorFromStatusPage = `-- name: DetachMonitorFromStatusPage :exec
DELETE FROM status_page_monitors
WHERE status_page_id = ?1
  AND monitor_id = ?2
`

type DetachMonitorFromStatusPageParams struct {
	StatusPageID int64 `json:"status_page_id"`
	MonitorID    int64 `json:"monitor_id"`
}

func (q *Queries) DetachMonitorFromStatusPage(ctx context.Context, arg DetachMonitorFromStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, detachMonitorFromStatusPage, arg.StatusPageID, arg.MonitorID)
	return err
}

const listMonitorsByStatusPage = `-- name: ListMonitorsByStatusPage :many
SELECT m.id, m.user_id, m.name, m.type, m.target, m.interval, m.timeout, m.enabled, m.created_at, m.next_check_at, m.confirmations
FROM monitors m
JOIN status_page_monitors spm ON spm.monitor_id = m.id
WHERE spm.status_page_id = ?1
ORDER BY m.name
`

func (q *Queries) ListMonitorsByStatusPage(ctx context.Context, statusPageID int64) ([]*Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorsByStatusPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Interval,
			&i.Timeout,
			&i.Enabled,
			&i.CreatedAt,
			&i.NextCheckAt,
			&i.Confirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPagesByMonitor = `-- name: ListStatusPagesByMonitor :many
SELECT sp.id, sp.user_id, sp.name, sp.slug, sp.public
FROM status_pages sp
JOIN status_page_monitors spm ON spm.status_page_id = sp.id
WHERE spm.monitor_id = ?1
ORDER BY sp.id
`

func (q *Queries) ListStatusPagesByMonitor(ctx context.Context, monitorID int64) ([]*StatusPage, error) {
	rows, err := q.db.QueryContext(ctx, listStatusPagesByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
