// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_pages.sql

package mapping

import (
	"context"
	"database/sql"
)

const createStatusPage = `-- name: CreateStatusPage :one
INSERT INTO status_pages (
    user_id,
    name,
    slug,
    public
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, user_id, name, slug, public
`

type CreateStatusPageParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	Public int64  `json:"public"`
}

func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (*StatusPage, error) {
	row := q.db.QueryRowContext(ctx, createStatusPage,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Public,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Public,
	)
	return &i, err
}

const deleteStatusPage = `-- name: DeleteStatusPage :exec
DELETE FROM status_pages
WHERE id = ?1
  AND user_id = ?2
`

type DeleteStatusPageParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteStatusPage(ctx context.Context, arg DeleteStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, deleteStatusPage, arg.ID, arg.UserID)
	return err
}

const getPublicStatusPageBySlug = `-- name: GetPublicStatusPageBySlug :one
SELECT sp.id, sp.user_id, sp.name, sp.slug, sp.public
FROM status_pages sp
WHERE sp.slug = ?1
  AND sp.public = 1
`

func (q *Queries) GetPublicStatusPageBySlug(ctx context.Context, slug string) (*StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getPublicStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Public,
	)
	return &i, err
}

const getStatusPageById = `-- name: GetStatusPageById :one
SELECT sp.id, sp.user_id, sp.name, sp.slug, sp.public
FROM status_pages sp
WHERE sp.id = ?1
`

func (q *Queries) GetStatusPageById(ctx context.Context, id int64) (*StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageById, id)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Public,
	)
	return &i, err
}

const getStatusPageByIdAndUser = `-- name: GetStatusPageByIdAndUser :one
SELECT sp.id, sp.user_id, sp.name, sp.slug, sp.public
FROM status_pages sp
WHERE sp.id = ?1
  AND sp.user_id = ?2
`

type GetStatusPageByIdAndUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetStatusPageByIdAndUser(ctx context.Context, arg GetStatusPageByIdAndUserParams) (*StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageByIdAndUser, arg.ID, arg.UserID)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Public,
	)
	return &i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT sp.id, sp.user_id, sp.name, sp.slug, sp.public
FROM status_pages sp
WHERE sp.slug = ?1
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (*StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Public,
	)
	return &i, err
}

const listStatusPagesByUser = `-- name: ListStatusPagesByUser :many
SELECT sp.id, sp.user_id, sp.name, sp.slug, sp.public
FROM status_pages sp
WHERE sp.user_id = ?1
ORDER BY sp.id DESC
`

func (q *Queries) ListStatusPagesByUser(ctx context.Context, userID string) ([]*StatusPage, error) {
	rows, err := q.db.QueryContext(ctx, listStatusPagesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatusPage = `-- name: UpdateStatusPage :one
UPDATE status_pages
SET name   = COALESCE(?1, name),
    slug   = COALESCE(?2, slug),
    public = COALESCE(?3, public)
WHERE id = ?4
  AND user_id = ?5
RETURNING id, user_id, name, slug, public
`

type UpdateStatusPageParams struct {
	Name   sql.NullString `json:"name"`
	Slug   sql.NullString `json:"slug"`
	Public sql.NullInt64  `json:"public"`
	ID     int64          `json:"id"`
	UserID string         `json:"user_id"`
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (*StatusPage, error) {
	row := q.db.QueryRowContext(ctx, updateStatusPage,
		arg.Name,
		arg.Slug,
		arg.Public,
		arg.ID,
		arg.UserID,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Public,
	)
	return &i, err
}
