// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uptime.sql

package mapping

import (
	"context"
)

const deleteOldMonitorUptimeHourly = `-- name: DeleteOldMonitorUptimeHourly :exec
DELETE FROM monitor_uptime_hourly
WHERE hour_start < ?1
`

func (q *Queries) DeleteOldMonitorUptimeHourly(ctx context.Context, before string) error {
	_, err := q.db.ExecContext(ctx, deleteOldMonitorUptimeHourly, before)
	return err
}

const listMonitorUptimeHourlySince = `-- name: ListMonitorUptimeHourlySince :many
SELECT monitor_id, hour_start, ok, total
FROM monitor_uptime_hourly
WHERE monitor_id = ?1
  AND hour_start >= ?2
ORDER BY hour_start ASC
`

type ListMonitorUptimeHourlySinceParams struct {
	MonitorID int64  `json:"monitor_id"`
	Since     string `json:"since"`
}

func (q *Queries) ListMonitorUptimeHourlySince(ctx context.Context, arg ListMonitorUptimeHourlySinceParams) ([]*MonitorUptimeHourly, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorUptimeHourlySince, arg.MonitorID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MonitorUptimeHourly{}
	for rows.Next() {
		var i MonitorUptimeHourly
		if err := rows.Scan(
			&i.MonitorID,
			&i.HourStart,
			&i.Ok,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonitorUptimeHourly = `-- name: UpsertMonitorUptimeHourly :exec
INSERT INTO monitor_uptime_hourly (monitor_id, hour_start, ok, total)
VALUES (
    ?1,
    ?2,
    ?3,
    1
)
ON CONFLICT (monitor_id, hour_start) DO UPDATE SET
    ok = ok + excluded.ok,
    total = total + 1
`

type UpsertMonitorUptimeHourlyParams struct {
	MonitorID int64  `json:"monitor_id"`
	HourStart string `json:"hour_start"`
	OkInc     int64  `json:"ok_inc"`
}

func (q *Queries) UpsertMonitorUptimeHourly(ctx context.Context, arg UpsertMonitorUptimeHourlyParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonitorUptimeHourly, arg.MonitorID, arg.HourStart, arg.OkInc)
	return err
}
