// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package mapping

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    password_hash,
    role,
    api_key
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, email, username, password_hash, role, status, api_key, last_login_at, last_login_ip, created_at, updated_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	ApiKey       sql.NullString `json:"api_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.ApiKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApiKey,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET status = 'inactive'
WHERE id = ?1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getListUser = `-- name: GetListUser :many
SELECT u.id, u.email, u.username, u.password_hash, u.role, u.status, u.api_key, u.last_login_at, u.last_login_ip, u.created_at, u.updated_at
FROM users u
ORDER BY u.created_at DESC
`

func (q *Queries) GetListUser(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, getListUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.ApiKey,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListUserByRole = `-- name: GetListUserByRole :many
SELECT u.id, u.email, u.username, u.password_hash, u.role, u.status, u.api_key, u.last_login_at, u.last_login_ip, u.created_at, u.updated_at
FROM users u
WHERE u.role = ?1
ORDER BY u.created_at DESC
`

func (q *Queries) GetListUserByRole(ctx context.Context, role string) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, getListUserByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.ApiKey,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT u.id, u.email, u.username, u.password_hash, u.role, u.status, u.api_key, u.last_login_at, u.last_login_ip, u.created_at, u.updated_at
FROM users u
WHERE u.api_key = ?1
  AND u.status = 'active'
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey sql.NullString) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApiKey,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.email, u.username, u.password_hash, u.role, u.status, u.api_key, u.last_login_at, u.last_login_ip, u.created_at, u.updated_at
FROM users u
WHERE lower(u.email) = lower(?1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApiKey,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserById = `-- name: GetUserById :one
SELECT u.id, u.email, u.username, u.password_hash, u.role, u.status, u.api_key, u.last_login_at, u.last_login_ip, u.created_at, u.updated_at
FROM users u
WHERE u.id = ?1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApiKey,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT u.id, u.email, u.username, u.password_hash, u.role, u.status, u.api_key, u.last_login_at, u.last_login_ip, u.created_at, u.updated_at
FROM users u
WHERE lower(u.username) = lower(?1)
`

func (q *Queries) GetUserByUserName(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApiKey,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserSelectList = `-- name: GetUserSelectList :many
SELECT (username || '(' || email || ')') AS title,
       id AS value
FROM users
WHERE lower(username) LIKE '%' || lower(COALESCE(?1, '')) || '%'
   OR lower(email) LIKE '%' || lower(COALESCE(?1, '')) || '%'
   OR id LIKE '%' || COALESCE(?1, '') || '%'
ORDER BY id
LIMIT 10
`

type GetUserSelectListRow struct {
	Title interface{} `json:"title"`
	Value string      `json:"value"`
}

func (q *Queries) GetUserSelectList(ctx context.Context, name interface{}) ([]*GetUserSelectListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSelectList, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUserSelectListRow{}
	for rows.Next() {
		var i GetUserSelectListRow
		if err := rows.Scan(&i.Title, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActive = `-- name: SetActive :exec
UPDATE users
SET status = 'active'
WHERE id = ?1
`

func (q *Queries) SetActive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setActive, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = datetime('now'),
    last_login_ip = ?1
WHERE id = ?2
`

type UpdateLastLoginParams struct {
	Ip sql.NullString `json:"ip"`
	ID string         `json:"id"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, arg.Ip, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email         = COALESCE(?1, email),
    username      = COALESCE(?2, username),
    password_hash = COALESCE(?3, password_hash),
    role          = COALESCE(?4, role),
    status        = COALESCE(?5, status),
    api_key       = COALESCE(?6, api_key)
WHERE id = ?7
RETURNING id, email, username, password_hash, role, status, api_key, last_login_at, last_login_ip, created_at, updated_at
`

type UpdateUserParams struct {
	Email        sql.NullString `json:"email"`
	Username     sql.NullString `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         sql.NullString `json:"role"`
	Status       sql.NullString `json:"status"`
	ApiKey       sql.NullString `json:"api_key"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.ApiKey,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApiKey,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
